[tool.poetry]
name = "finalproject"
version = "0.1.0"
description = ""
authors = ["dadporosya <ilja.amogus@gmail.com>"]


readme = "README.md"
package-mode = false
requires-poetry = "2.3.2"

[tool.poetry.dependencies]
python = "3.13.12"
#
telebot = "0.0.5"
pydantic = "2.12.5"
pydantic-settings = "2.13.1"



[dependency-groups]
dev = [
    "pylint (==4.0.5)",
    "ruff (==0.15.7)",
    "mypy (==1.19.1)",
]


[tool.pylint]
disable = [
    "invalid-name",
]
ignore = [
    "temp",
]


[tool.mypy]
python_version="3.13"
exclude = "^temp/"
#max-line-length = 100


[tool.ruff]
exclude = [
    "temp"
]
line-length = 100
indent-width = 4
target-version = "py311"
