[tool.poetry]
name = "finalproject"
version = "0.1.0"
description = ""
authors = ["dadporosya <ilja.amogus@gmail.com>"]


readme = "README.md"
package-mode = false
requires-poetry = "2.3.2"

[tool.poetry.dependencies]
python = "3.13.12"
#
telebot = "0.0.5"



[dependency-groups]
dev = [
    "pylint (==4.0.5)"
]
